const slugify = require("slugify");

async function tasks() {
  return [
    {
      code: 1,
      title: "Ceiling Lime Paint",
      description: "Application of lime paint on ceilings",
      task_group: "Paintings",
      status: "uninitiated",
      unit: "m2",
      total_budget_qty: 29,
      total_budget_hrs: 6,
      total_labour_cost: 126,
      budget_perf_ratio: 0.21,
      acum_perf_ratio: 0,
      cost_overrun_est: 0,
      slug: slugify("Ceiling Lime Paint", {
        replacement: "-",
        lower: true,
      }),
    },
    {
      code: 2,
      title: "Wall Lime Paint",
      description: "Application of lime paint on walls",
      task_group: "Paintings",
      status: "uninitiated",
      unit: "m2",
      total_budget_qty: 58,
      total_budget_hrs: 12,
      total_labour_cost: 253,
      budget_perf_ratio: 0.21,
      acum_perf_ratio: 0,
      cost_overrun_est: 0,
      slug: slugify("Wall Lime Paint", {
        replacement: "-",
        lower: true,
      }),
    },
    {
      code: 3,
      title: "Ceiling Enamel Paint",
      description: "Application of enamel paint on ceilings",
      task_group: "Paintings",
      status: "uninitiated",
      unit: "m2",
      total_budget_qty: 62,
      total_budget_hrs: 19,
      total_labour_cost: 400,
      budget_perf_ratio: 0.31,
      acum_perf_ratio: 0,
      cost_overrun_est: 0,
      slug: slugify("Ceiling Enamel Paint", {
        replacement: "-",
        lower: true,
      }),
    },
    {
      code: 4,
      title: "Wall Enamel Paint",
      description: "Application of enamel paint on walls",
      task_group: "Paintings",
      status: "uninitiated",
      unit: "m2",
      total_budget_qty: 83,
      total_budget_hrs: 17,
      total_labour_cost: 358,
      budget_perf_ratio: 0.2,
      acum_perf_ratio: 0,
      cost_overrun_est: 0,
      slug: slugify("Wall Enamel Paint", {
        replacement: "-",
        lower: true,
      }),
    },
    {
      code: 5,
      title: "Solid Door Enamel Paint",
      description: "Application of enamel paint on solid doors",
      task_group: "Paintings",
      status: "uninitiated",
      unit: "m2",
      total_budget_qty: 50,
      total_budget_hrs: 60,
      total_labour_cost: 1263,
      budget_perf_ratio: 1.2,
      acum_perf_ratio: 0,
      cost_overrun_est: 0,
      slug: slugify("Solid Door Enamel Paint", {
        replacement: "-",
        lower: true,
      }),
    },
    {
      code: 6,
      title: "Glass Opening Enamel Paint",
      description: "Application of enamel paint on glass openings",
      task_group: "Paintings",
      status: "uninitiated",
      unit: "m2",
      total_budget_qty: 12,
      total_budget_hrs: 20,
      total_labour_cost: 421,
      budget_perf_ratio: 1.67,
      acum_perf_ratio: 0,
      cost_overrun_est: 0,
      slug: slugify("Glass Opening Enamel Paint", {
        replacement: "-",
        lower: true,
      }),
    },
    {
      code: 7,
      title: "Curtain Enamel Paint",
      description: "Application of enamel paint on curtains",
      task_group: "Paintings",
      status: "uninitiated",
      unit: "m2",
      total_budget_qty: 81,
      total_budget_hrs: 195,
      total_labour_cost: 4105,
      budget_perf_ratio: 2.41,
      acum_perf_ratio: 0,
      cost_overrun_est: 0,
      slug: slugify("Curtain Enamel Paint", {
        replacement: "-",
        lower: true,
      }),
    },
    {
      code: 8,
      title: "Ceiling Water Paint",
      description: "Application of water-based paint on ceilings",
      task_group: "Paintings",
      status: "uninitiated",
      unit: "m2",
      total_budget_qty: 81,
      total_budget_hrs: 17,
      total_labour_cost: 358,
      budget_perf_ratio: 0.21,
      acum_perf_ratio: 0,
      cost_overrun_est: 0,
      slug: slugify("Ceiling Water Paint", {
        replacement: "-",
        lower: true,
      }),
    },
    {
      code: 9,
      title: "Wall Water Paint",
      description: "Application of water-based paint on walls",
      task_group: "Paintings",
      status: "uninitiated",
      unit: "m2",
      total_budget_qty: 95,
      total_budget_hrs: 19,
      total_labour_cost: 400,
      budget_perf_ratio: 0.2,
      acum_perf_ratio: 0,
      cost_overrun_est: 0,
      slug: slugify("Wall Water Paint", {
        replacement: "-",
        lower: true,
      }),
    },
    {
      code: 10,
      title: "Trench up to 1.00 m: Sandy Vegetal Soil",
      description: "Hand excavation of trench in sandy vegetal soil up to 1.00 m depth",
      task_group: "Hand Excavation",
      status: "completed",
      unit: "m3",
      total_budget_qty: 77,
      total_budget_hrs: 208,
      total_labour_cost: 4379,
      budget_perf_ratio: 2.7,
      acum_perf_ratio: 0,
      cost_overrun_est: 0,
      slug: slugify("Trench up to 1.00 m: Sandy Vegetal Soil", {
        replacement: "-",
        lower: true,
      }),
    },
    {
      code: 11,
      title: "1.00 to 2.00 m Pit: Sandy Vegetal Soil",
      description: "Hand excavation of pit in sandy vegetal soil from 1.00 m to 2.00 m depth",
      task_group: "Hand Excavation",
      status: "completed",
      unit: "m3",
      total_budget_qty: 43,
      total_budget_hrs: 134,
      total_labour_cost: 2821,
      budget_perf_ratio: 3.12,
      acum_perf_ratio: 0,
      cost_overrun_est: 0,
      slug: slugify("1.00 to 2.00 m Pit: Sandy Vegetal Soil", {
        replacement: "-",
        lower: true,
      }),
    },
    {
      code: 12,
      title: "1.00 to 2.00 m Pit: Clayey Sandy Soil",
      description:
        "Hand excavation of pit in clayey sandy soil from 1.00 m to 2.00 m depth (Type T)",
      task_group: "Hand Excavation",
      status: "completed",
      unit: "m3",
      total_budget_qty: 7,
      total_budget_hrs: 19,
      total_labour_cost: 400,
      budget_perf_ratio: 2.71,
      acum_perf_ratio: 0,
      cost_overrun_est: 0,
      slug: slugify("1.00 to 2.00 m Pit: Clayey Sandy Soil", {
        replacement: "-",
        lower: true,
      }),
    },
    {
      code: 13,
      title: "2.00 to 4.00 m Pit: Sandy Clay Soil",
      description: "Hand excavation of pit in sandy clay soil from 2.00 m to 4.00 m depth (Type l)",
      task_group: "Hand Excavation",
      status: "completed",
      unit: "m3",
      total_budget_qty: 62,
      total_budget_hrs: 360,
      total_labour_cost: 7579,
      budget_perf_ratio: 5.81,
      acum_perf_ratio: 0,
      cost_overrun_est: 0,
      slug: slugify("2.00 to 4.00 m Pit: Sandy Clay Soil", {
        replacement: "-",
        lower: true,
      }),
    },
    {
      code: 14,
      title: "1.00 to 2.00 m Pit: Compact Clay",
      description: "Hand excavation of pit in compact clay from 1.00 m to 2.00 m depth",
      task_group: "Hand Excavation",
      status: "completed",
      unit: "m3",
      total_budget_qty: 28,
      total_budget_hrs: 163,
      total_labour_cost: 3432,
      budget_perf_ratio: 5.82,
      acum_perf_ratio: 0,
      cost_overrun_est: 0,
      slug: slugify("1.00 to 2.00 m Pit: Compact Clay", {
        replacement: "-",
        lower: true,
      }),
    },
    {
      code: 15,
      title: "2.00 to 4.00 m Pit: Compact Clay",
      description: "Hand excavation of pit in compact clay from 2.00 m to 4.00 m depth",
      task_group: "Hand Excavation",
      status: "completed",
      unit: "m3",
      total_budget_qty: 19,
      total_budget_hrs: 168,
      total_labour_cost: 3537,
      budget_perf_ratio: 8.84,
      acum_perf_ratio: 0,
      cost_overrun_est: 0,
      slug: slugify("2.00 to 4.00 m Pit: Compact Clay", {
        replacement: "-",
        lower: true,
      }),
    },
    {
      code: 16,
      title: "2.00 to 4.00 m Pit",
      description: "Hand excavation of pit from 2.00 m to 4.00 m depth",
      task_group: "Hand Excavation",
      status: "completed",
      unit: "m3",
      total_budget_qty: 92,
      total_budget_hrs: 939,
      total_labour_cost: 19768,
      budget_perf_ratio: 10.21,
      acum_perf_ratio: 0,
      cost_overrun_est: 0,
      slug: slugify("2.00 to 4.00 m Pit", {
        replacement: "-",
        lower: true,
      }),
    },
    {
      code: 17,
      title: "2.00 to 4.00 m Pit",
      description: "Hand excavation of pit from 2.00 m to 4.00 m depth",
      task_group: "Hand Excavation",
      status: "completed",
      unit: "m3",
      total_budget_qty: 21,
      total_budget_hrs: 297,
      total_labour_cost: 6253,
      budget_perf_ratio: 14.14,
      acum_perf_ratio: 0,
      cost_overrun_est: 0,
      slug: slugify("2.00 to 4.00 m Pit", {
        replacement: "-",
        lower: true,
      }),
    },
    {
      code: 18,
      title: "2.00 to 4.00 m Pit",
      description: "Hand excavation of pit from 2.00 m to 4.00 m depth",
      task_group: "Hand Excavation",
      status: "completed",
      unit: "m3",
      total_budget_qty: 20,
      total_budget_hrs: 564,
      total_labour_cost: 11874,
      budget_perf_ratio: 28.2,
      acum_perf_ratio: 0,
      cost_overrun_est: 0,
      slug: slugify("2.00 to 4.00 m Pit", {
        replacement: "-",
        lower: true,
      }),
    },
    {
      code: 19,
      title: "Machine Excavation",
      description: "Machine excavation",
      task_group: "Machine Excavation",
      status: "completed",
      unit: "m3",
      total_budget_qty: 1200,
      total_budget_hrs: 120,
      total_labour_cost: 2526,
      budget_perf_ratio: 0.1,
      acum_perf_ratio: 0,
      cost_overrun_est: 0,
      slug: slugify("Machine Excavation", {
        replacement: "-",
        lower: true,
      }),
    },
    {
      code: 20,
      title: "Cyclopean Concrete Footings",
      description: "Pouring cyclopean concrete footings",
      task_group: "Concrete",
      status: "completed",
      unit: "m3",
      total_budget_qty: 22,
      total_budget_hrs: 185,
      total_labour_cost: 3895,
      budget_perf_ratio: 8.41,
      acum_perf_ratio: 0,
      cost_overrun_est: 0,
      slug: slugify("Cyclopean Concrete Footings", {
        replacement: "-",
        lower: true,
      }),
    },
    {
      code: 21,
      title: "Cyclopean Concrete Walls",
      description: "Pouring cyclopean concrete walls",
      task_group: "Concrete",
      status: "pending",
      unit: "m3",
      total_budget_qty: 48,
      total_budget_hrs: 1460,
      total_labour_cost: 30737,
      budget_perf_ratio: 30.42,
      acum_perf_ratio: 0,
      cost_overrun_est: 0,
      slug: slugify("Cyclopean Concrete Walls", {
        replacement: "-",
        lower: true,
      }),
    },
    {
      code: 22,
      title: "Reinforced Concrete Footings",
      description: "Pouring reinforced concrete footings",
      task_group: "Concrete",
      status: "pending",
      unit: "m3",
      total_budget_qty: 31,
      total_budget_hrs: 726,
      total_labour_cost: 15284,
      budget_perf_ratio: 23.42,
      acum_perf_ratio: 0,
      cost_overrun_est: 0,
      slug: slugify("Reinforced Concrete Footings", {
        replacement: "-",
        lower: true,
      }),
    },
    {
      code: 23,
      title: "Retaining Walls",
      description: "Pouring concrete retaining walls",
      task_group: "Concrete",
      status: "pending",
      unit: "m3",
      total_budget_qty: 12,
      total_budget_hrs: 539,
      total_labour_cost: 11347,
      budget_perf_ratio: 44.92,
      acum_perf_ratio: 0,
      cost_overrun_est: 0,
      slug: slugify("Retaining Walls", {
        replacement: "-",
        lower: true,
      }),
    },
    {
      code: 24,
      title: "Foundation Beams",
      description: "Pouring foundation beams",
      task_group: "Concrete",
      status: "pending",
      unit: "m3",
      total_budget_qty: 21,
      total_budget_hrs: 870,
      total_labour_cost: 18316,
      budget_perf_ratio: 41.43,
      acum_perf_ratio: 0,
      cost_overrun_est: 0,
      slug: slugify("Foundation Beams", {
        replacement: "-",
        lower: true,
      }),
    },
    {
      code: 25,
      title: "Columns",
      description: "Pouring concrete columns",
      task_group: "Concrete",
      status: "uninitiated",
      unit: "m3",
      total_budget_qty: 38,
      total_budget_hrs: 2926,
      total_labour_cost: 61600,
      budget_perf_ratio: 77,
      acum_perf_ratio: 0,
      cost_overrun_est: 0,
      slug: slugify("Pouring concrete columns", {
        replacement: "-",
        lower: true,
      }),
    },
    {
      code: 26,
      title: "Intermediate Beams",
      description: "Pouring concrete intermediate beams",
      task_group: "Concrete",
      status: "uninitiated",
      unit: "m3",
      total_budget_qty: 47,
      total_budget_hrs: 2816,
      total_labour_cost: 59284,
      budget_perf_ratio: 59.91,
      acum_perf_ratio: 0,
      cost_overrun_est: 0,
      slug: slugify("Intermediate Beams", {
        replacement: "-",
        lower: true,
      }),
    },
    {
      code: 27,
      title: "Solid Slabs",
      description: "Pouring solid concrete slabs",
      task_group: "Concrete",
      status: "uninitiated",
      unit: "m3",
      total_budget_qty: 47,
      total_budget_hrs: 2111,
      total_labour_cost: 44442,
      budget_perf_ratio: 44.91,
      acum_perf_ratio: 0,
      cost_overrun_est: 0,
      slug: slugify("Solid Slab", {
        replacement: "-",
        lower: true,
      }),
    },
    {
      code: 28,
      title: "Ribbed Slabs",
      description: "Pouring ribbed concrete slabs",
      task_group: "Concrete",
      status: "uninitiated",
      unit: "m3",
      total_budget_qty: 33,
      total_budget_hrs: 1614,
      total_labour_cost: 33979,
      budget_perf_ratio: 48.91,
      acum_perf_ratio: 0,
      cost_overrun_est: 0,
      slug: slugify("Ribbed Slabs", {
        replacement: "-",
        lower: true,
      }),
    },
    {
      code: 29,
      title: "Stairs",
      description: "Pouring concrete stairs",
      task_group: "Concrete",
      status: "uninitiated",
      unit: "m3",
      total_budget_qty: 16,
      total_budget_hrs: 1452,
      total_labour_cost: 30568,
      budget_perf_ratio: 90.75,
      acum_perf_ratio: 0,
      cost_overrun_est: 0,
      slug: slugify("Stairs", {
        replacement: "-",
        lower: true,
      }),
    },
    {
      code: 30,
      title: "Water Tanks",
      description: "Pouring concrete water tanks",
      task_group: "Concrete",
      status: "uninitiated",
      unit: "m3",
      total_budget_qty: 17,
      total_budget_hrs: 1258,
      total_labour_cost: 26484,
      budget_perf_ratio: 74,
      acum_perf_ratio: 0,
      cost_overrun_est: 0,
      slug: slugify("Water Tanks", {
        replacement: "-",
        lower: true,
      }),
    },
    {
      code: 31,
      title: "Concrete Piles",
      description: "Pouring concrete piles",
      task_group: "Concrete",
      status: "pending",
      unit: "un",
      total_budget_qty: 57,
      total_budget_hrs: 1254,
      total_labour_cost: 26400,
      budget_perf_ratio: 22,
      acum_perf_ratio: 0,
      cost_overrun_est: 0,
      slug: slugify("Concrete Piles", {
        replacement: "-",
        lower: true,
      }),
    },
    {
      code: 32,
      title: "Raft Foundation with Mesh",
      description: "Pouring raft foundation with mesh",
      task_group: "Concrete",
      status: "pending",
      unit: "m2",
      total_budget_qty: 61,
      total_budget_hrs: 1342,
      total_labour_cost: 28253,
      budget_perf_ratio: 22,
      acum_perf_ratio: 0,
      cost_overrun_est: 0,
      slug: slugify("Raft Foundation with Mesh", {
        replacement: "-",
        lower: true,
      }),
    },
    {
      code: 33,
      title: "0.07 Blocks",
      description: "Laying 0.07 blocks",
      task_group: "Masonry",
      status: "uninitiated",
      unit: "m2",
      total_budget_qty: 30,
      total_budget_hrs: 30,
      total_labour_cost: 632,
      budget_perf_ratio: 1,
      acum_perf_ratio: 0,
      cost_overrun_est: 0,
      slug: slugify("0.07 Blocks", {
        replacement: "-",
        lower: true,
      }),
    },
    {
      code: 34,
      title: "0.12 Blocks",
      description: "Laying 0.12 blocks",
      task_group: "Masonry",
      status: "uninitiated",
      unit: "m2",
      total_budget_qty: 40,
      total_budget_hrs: 52,
      total_labour_cost: 1095,
      budget_perf_ratio: 1.3,
      acum_perf_ratio: 0,
      cost_overrun_est: 0,
      slug: slugify("0.12 Blocks", {
        replacement: "-",
        lower: true,
      }),
    },
    {
      code: 35,
      title: "0.20 Blocks",
      description: "Laying 0.20 blocks",
      task_group: "Masonry",
      status: "uninitiated",
      unit: "m2",
      total_budget_qty: 73,
      total_budget_hrs: 110,
      total_labour_cost: 2316,
      budget_perf_ratio: 1.51,
      acum_perf_ratio: 0,
      cost_overrun_est: 0,
      slug: slugify("0.20 Blocks", {
        replacement: "-",
        lower: true,
      }),
    },
    {
      code: 36,
      title: "Exposed Brick",
      description: "Laying exposed bricks",
      task_group: "Masonry",
      status: "uninitiated",
      unit: "m2",
      total_budget_qty: 34,
      total_budget_hrs: 123,
      total_labour_cost: 2589,
      budget_perf_ratio: 3.62,
      acum_perf_ratio: 0,
      cost_overrun_est: 0,
      slug: slugify("Exposed Brick", {
        replacement: "-",
        lower: true,
      }),
    },
    {
      code: 37,
      title: "Double-Wall Exposed Brick",
      description: "Laying double-wall exposed bricks",
      task_group: "Masonry",
      status: "uninitiated",
      unit: "m2",
      total_budget_qty: 4,
      total_budget_hrs: 23,
      total_labour_cost: 484,
      budget_perf_ratio: 5.75,
      acum_perf_ratio: 0,
      cost_overrun_est: 0,
      slug: slugify("Double-Wall Exposed Brick", {
        replacement: "-",
        lower: true,
      }),
    },
  ];
}

module.exports = tasks;
